apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-unit-test
  annotations:
    tekton.dev/title: "Go Unit Test Task"
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: registry.access.redhat.com/ubi9/go-toolset@sha256:c3a9c5c7fb226f6efcec2424dd30c38f652156040b490c9eca5ac5b61d8dc3ca
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/usr/bin/env sh
        go test $(go list ./... | grep -v github.com/sigstore/gitsign/pkg/version)

# This file bundles the unit tests for gitsign. 
# If any changes are made to this file, it must be pushed to Quay using the following command:
# 'tkn bundle push quay.io/securesign/gitsign-unit-test:latest -f .tekton/gitsign-unit-test.yaml'.